"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$cmd_duration\
$time\
$status\n \
$character
"""

palette = "rose-pine"

add_newline = false

continuation_prompt = "[>> ](iris)"

[status]
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style)'
disabled = false
symbol = 'âœ˜ '
success_symbol = 'âœ“'
success_style = "fg:foam"

[cmd_duration]
format = "[ $duration]($style)"
min_time = 1_000

[character]
success_symbol = '[ï…•](bold fg:iris)'
error_symbol = "[ï…•](bold fg:iris)"
vicmd_symbol = "[ğ‘½](bold fg:iris)"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
format = "[$path]($style)"
style = "fg:pine"
truncation_length = 0
truncation_symbol = "â€¦/"
truncate_to_repo = false

[directory.substitutions]
Documents = "ó°ˆ™"
Downloads = "ï€™ "
Music = "ï€ "
Pictures = "ï€¾ "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:foam"
symbol = "ï˜"

[git_status]
disabled = false
style = "fg:love"
format = '([$all_status$ahead_behind]($style)) '
up_to_date = '[ âœ“ ](fg:iris)'
untracked = '[?\($count\)](fg:gold)'
stashed = '[\$](fg:iris)'
modified = '[!\($count\)](fg:gold)'
renamed = '[Â»\($count\)](fg:iris)'
deleted = '[âœ˜\($count\)](style)'
staged = '[++\($count\)](fg:gold)'
ahead = '[â‡¡\(${count}\)](fg:foam)'
diverged = 'â‡•[\[](fg:iris)[â‡¡\(${ahead_count}\)](fg:foam)[â‡£\(${behind_count}\)](fg:rose)[\]](fg:iris)'
behind = '[â‡£\(${count}\)](fg:rose)'

[time]
disabled = false
format = "[ $time ]($style)"
style = "fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[ ó°§± $user ]($style)"
show_always = true
style_root = "fg:iris"
style_user = "fg:iris"

# Languages

[c]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î˜ "

[elixir]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î‰µ "

[elm]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î˜¬ "

[golang]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î˜§ "

[haskell]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î· "

[java]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î‰– "

[julia]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î˜¤ "

[nodejs]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "ó°™ "

[nim]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "ó°†¥ "

[rust]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "î¨ "

[scala]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = "îœ· "

[python]
style = "fg:pine"
format = "[ $symbol$version ]($style)"
disabled = false
symbol = 'îœ¼ '

[conda]
style = "fg:pine"
format = "[ $symbol$environment ]($style)"
disabled = false
symbol = 'ğŸ…’ '
